import { parsePhoneNumber } from "libphonenumber-js";

// TRAI Telecom Circle mapping — first 4 digits → { operator, circle }
// Duplicates removed; one canonical entry per prefix
const PREFIX_MAP: Record<string, { operator: string; circle: string }> = {
  // ── Jio ──────────────────────────────────────────────
  "6000": { operator: "Jio", circle: "UP West" },
  "6001": { operator: "Jio", circle: "UP West" },
  "6002": { operator: "Jio", circle: "UP East" },
  "6003": { operator: "Jio", circle: "UP East" },
  "6004": { operator: "Jio", circle: "Bihar" },
  "6005": { operator: "Jio", circle: "Bihar" },
  "6006": { operator: "Jio", circle: "West Bengal" },
  "6007": { operator: "Jio", circle: "West Bengal" },
  "6200": { operator: "Jio", circle: "Rajasthan" },
  "6201": { operator: "Jio", circle: "Rajasthan" },
  "6202": { operator: "Jio", circle: "Rajasthan" },
  "6260": { operator: "Jio", circle: "Madhya Pradesh" },
  "6261": { operator: "Jio", circle: "Madhya Pradesh" },
  "6262": { operator: "Jio", circle: "Madhya Pradesh" },
  "6263": { operator: "Jio", circle: "Madhya Pradesh" },
  "6350": { operator: "Jio", circle: "Gujarat" },
  "6351": { operator: "Jio", circle: "Gujarat" },
  "6352": { operator: "Jio", circle: "Gujarat" },
  "6353": { operator: "Jio", circle: "Gujarat" },
  "6354": { operator: "Jio", circle: "Gujarat" },
  "6355": { operator: "Jio", circle: "Gujarat" },
  "7000": { operator: "Jio", circle: "Madhya Pradesh" },
  "7001": { operator: "Jio", circle: "Madhya Pradesh" },
  "7002": { operator: "Jio", circle: "Assam" },
  "7003": { operator: "Jio", circle: "West Bengal" },
  "7004": { operator: "Jio", circle: "West Bengal" },
  "7005": { operator: "Jio", circle: "Jammu & Kashmir" },
  "7006": { operator: "Jio", circle: "Jammu & Kashmir" },
  "7007": { operator: "Jio", circle: "Jammu & Kashmir" },
  "7008": { operator: "Jio", circle: "Odisha" },
  "7009": { operator: "Jio", circle: "Himachal Pradesh" },
  "7010": { operator: "Jio", circle: "Tamil Nadu" },
  "7011": { operator: "Jio", circle: "Delhi" },
  "7012": { operator: "Jio", circle: "Kerala" },
  "7013": { operator: "Jio", circle: "Andhra Pradesh" },
  "7014": { operator: "Jio", circle: "Rajasthan" },
  "7015": { operator: "Jio", circle: "Haryana" },
  "7016": { operator: "Jio", circle: "Karnataka" },
  "7017": { operator: "Jio", circle: "Maharashtra" },
  "7018": { operator: "Jio", circle: "Kerala" },
  "7019": { operator: "Jio", circle: "Karnataka" },
  "7020": { operator: "Jio", circle: "Maharashtra" },
  "7021": { operator: "Jio", circle: "Maharashtra" },
  "7022": { operator: "Jio", circle: "Karnataka" },
  "7023": { operator: "Jio", circle: "Rajasthan" },
  "7024": { operator: "Jio", circle: "Madhya Pradesh" },
  "7025": { operator: "Jio", circle: "Kerala" },
  "7026": { operator: "Jio", circle: "Gujarat" },
  "7028": { operator: "Jio", circle: "Maharashtra" },
  "7030": { operator: "Jio", circle: "Maharashtra" },
  "7031": { operator: "Jio", circle: "Gujarat" },
  "7032": { operator: "Jio", circle: "Telangana" },
  "7033": { operator: "Jio", circle: "West Bengal" },
  "7034": { operator: "Jio", circle: "Kerala" },
  "7035": { operator: "Jio", circle: "Andhra Pradesh" },
  "7036": { operator: "Jio", circle: "Telangana" },
  "7037": { operator: "Jio", circle: "UP West" },
  "7038": { operator: "Jio", circle: "Bihar" },
  "7039": { operator: "Jio", circle: "Tamil Nadu" },
  "7040": { operator: "Jio", circle: "Maharashtra" },
  "7041": { operator: "Jio", circle: "Gujarat" },
  "7042": { operator: "Jio", circle: "Delhi" },
  "7043": { operator: "Jio", circle: "Punjab" },
  "7044": { operator: "Jio", circle: "West Bengal" },
  "7045": { operator: "Jio", circle: "Maharashtra" },
  "7046": { operator: "Jio", circle: "Gujarat" },
  "7047": { operator: "Jio", circle: "UP West" },
  "7048": { operator: "Jio", circle: "Gujarat" },
  "7049": { operator: "Jio", circle: "Gujarat" },
  "7050": { operator: "Jio", circle: "UP East" },
  "7051": { operator: "Jio", circle: "UP East" },
  "7052": { operator: "Jio", circle: "Delhi" },
  "7053": { operator: "Jio", circle: "Punjab" },
  "7054": { operator: "Jio", circle: "Rajasthan" },
  "7055": { operator: "Jio", circle: "UP West" },
  "7056": { operator: "Jio", circle: "UP West" },
  "7057": { operator: "Jio", circle: "UP East" },
  "7058": { operator: "Jio", circle: "Maharashtra" },
  "7059": { operator: "Jio", circle: "UP East" },
  "7060": { operator: "Jio", circle: "UP West" },
  "7061": { operator: "Jio", circle: "UP East" },
  "7063": { operator: "Jio", circle: "West Bengal" },
  "7066": { operator: "Jio", circle: "Maharashtra" },
  "7067": { operator: "Jio", circle: "Maharashtra" },
  "7068": { operator: "Jio", circle: "Delhi" },
  "7069": { operator: "Jio", circle: "Maharashtra" },
  "7071": { operator: "Jio", circle: "Andhra Pradesh" },
  "7075": { operator: "Jio", circle: "Telangana" },
  "7077": { operator: "Jio", circle: "Bihar" },
  "7080": { operator: "Jio", circle: "UP East" },
  "7081": { operator: "Jio", circle: "UP East" },
  "7082": { operator: "Jio", circle: "Delhi" },
  "7083": { operator: "Jio", circle: "Delhi" },
  "7084": { operator: "Jio", circle: "UP West" },
  "7085": { operator: "Jio", circle: "Rajasthan" },
  "7086": { operator: "Jio", circle: "Assam" },
  "7087": { operator: "Jio", circle: "Punjab" },
  "7088": { operator: "Jio", circle: "UP West" },
  "7091": { operator: "Jio", circle: "UP East" },
  "7093": { operator: "Jio", circle: "Telangana" },
  "7095": { operator: "Jio", circle: "Karnataka" },
  "7096": { operator: "Jio", circle: "Tamil Nadu" },
  "7097": { operator: "Jio", circle: "Tamil Nadu" },
  "7099": { operator: "Jio", circle: "UP West" },
  // ── Airtel ───────────────────────────────────────────
  "8010": { operator: "Airtel", circle: "Delhi" },
  "8011": { operator: "Airtel", circle: "Delhi" },
  "8012": { operator: "Airtel", circle: "Tamil Nadu" },
  "8013": { operator: "Airtel", circle: "West Bengal" },
  "8014": { operator: "Airtel", circle: "West Bengal" },
  "8015": { operator: "Airtel", circle: "West Bengal" },
  "8016": { operator: "Airtel", circle: "West Bengal" },
  "8017": { operator: "Airtel", circle: "West Bengal" },
  "8018": { operator: "Airtel", circle: "Odisha" },
  "8019": { operator: "Airtel", circle: "Andhra Pradesh" },
  "8023": { operator: "Airtel", circle: "Karnataka" },
  "8025": { operator: "Airtel", circle: "Karnataka" },
  "8026": { operator: "Airtel", circle: "Karnataka" },
  "8028": { operator: "Airtel", circle: "Karnataka" },
  "8029": { operator: "Airtel", circle: "Karnataka" },
  "8030": { operator: "Airtel", circle: "Karnataka" },
  "8031": { operator: "Airtel", circle: "Karnataka" },
  "8032": { operator: "Airtel", circle: "Karnataka" },
  "8033": { operator: "Airtel", circle: "Karnataka" },
  "8034": { operator: "Airtel", circle: "Karnataka" },
  "8035": { operator: "Airtel", circle: "Karnataka" },
  "8036": { operator: "Airtel", circle: "Karnataka" },
  "8041": { operator: "Airtel", circle: "Karnataka" },
  "8042": { operator: "Airtel", circle: "Karnataka" },
  "8050": { operator: "Airtel", circle: "Karnataka" },
  "8051": { operator: "Airtel", circle: "Andhra Pradesh" },
  "8052": { operator: "Airtel", circle: "Andhra Pradesh" },
  "8053": { operator: "Airtel", circle: "Punjab" },
  "8054": { operator: "Airtel", circle: "Punjab" },
  "8055": { operator: "Airtel", circle: "Rajasthan" },
  "8056": { operator: "Airtel", circle: "Tamil Nadu" },
  "8057": { operator: "Airtel", circle: "Rajasthan" },
  "8058": { operator: "Airtel", circle: "UP East" },
  "8059": { operator: "Airtel", circle: "Rajasthan" },
  "8105": { operator: "Airtel", circle: "Karnataka" },
  "8106": { operator: "Airtel", circle: "Andhra Pradesh" },
  "8107": { operator: "Airtel", circle: "Rajasthan" },
  "8108": { operator: "Airtel", circle: "Maharashtra" },
  "8109": { operator: "Airtel", circle: "Madhya Pradesh" },
  "8110": { operator: "Airtel", circle: "Kerala" },
  "8111": { operator: "Airtel", circle: "Bihar" },
  "8112": { operator: "Airtel", circle: "Bihar" },
  "8113": { operator: "Airtel", circle: "Bihar" },
  "8114": { operator: "Airtel", circle: "Assam" },
  "8115": { operator: "Airtel", circle: "Northeast" },
  "8116": { operator: "Airtel", circle: "Haryana" },
  "8117": { operator: "Airtel", circle: "UP West" },
  "8118": { operator: "Airtel", circle: "UP East" },
  "8119": { operator: "Airtel", circle: "UP East" },
  "9810": { operator: "Airtel", circle: "Delhi" },
  "9811": { operator: "Airtel", circle: "Delhi" },
  "9812": { operator: "Airtel", circle: "Haryana" },
  "9813": { operator: "Airtel", circle: "Himachal Pradesh" },
  "9814": { operator: "Airtel", circle: "Punjab" },
  "9815": { operator: "Airtel", circle: "Punjab" },
  "9816": { operator: "Airtel", circle: "Himachal Pradesh" },
  "9817": { operator: "Airtel", circle: "Himachal Pradesh" },
  "9818": { operator: "Airtel", circle: "Delhi" },
  "9819": { operator: "Airtel", circle: "Mumbai" },
  "9820": { operator: "Airtel", circle: "Mumbai" },
  "9821": { operator: "Airtel", circle: "Mumbai" },
  "9822": { operator: "Airtel", circle: "Maharashtra" },
  "9823": { operator: "Airtel", circle: "Maharashtra" },
  "9824": { operator: "Airtel", circle: "Gujarat" },
  "9825": { operator: "Airtel", circle: "Gujarat" },
  "9826": { operator: "Airtel", circle: "Madhya Pradesh" },
  "9827": { operator: "Airtel", circle: "Madhya Pradesh" },
  "9828": { operator: "Airtel", circle: "Rajasthan" },
  "9829": { operator: "Airtel", circle: "Rajasthan" },
  "9830": { operator: "Airtel", circle: "Kolkata" },
  "9831": { operator: "Airtel", circle: "Kolkata" },
  "9832": { operator: "Airtel", circle: "West Bengal" },
  "9833": { operator: "Airtel", circle: "Mumbai" },
  "9834": { operator: "Airtel", circle: "Maharashtra" },
  "9835": { operator: "Airtel", circle: "Bihar" },
  "9836": { operator: "Airtel", circle: "West Bengal" },
  "9837": { operator: "Airtel", circle: "UP West" },
  "9838": { operator: "Airtel", circle: "UP East" },
  "9839": { operator: "Airtel", circle: "UP East" },
  "9840": { operator: "Airtel", circle: "Tamil Nadu" },
  "9841": { operator: "Airtel", circle: "Tamil Nadu" },
  "9842": { operator: "Airtel", circle: "Tamil Nadu" },
  "9843": { operator: "Airtel", circle: "Tamil Nadu" },
  "9844": { operator: "Airtel", circle: "Karnataka" },
  "9845": { operator: "Airtel", circle: "Karnataka" },
  "9846": { operator: "Airtel", circle: "Kerala" },
  "9847": { operator: "Airtel", circle: "Kerala" },
  "9848": { operator: "Airtel", circle: "Andhra Pradesh" },
  "9849": { operator: "Airtel", circle: "Andhra Pradesh" },
  "9850": { operator: "Airtel", circle: "Maharashtra" },
  "9851": { operator: "Airtel", circle: "Bihar" },
  "9852": { operator: "Airtel", circle: "Bihar" },
  "9853": { operator: "Airtel", circle: "Odisha" },
  "9854": { operator: "Airtel", circle: "Assam" },
  "9855": { operator: "Airtel", circle: "Punjab" },
  "9856": { operator: "Airtel", circle: "Jammu & Kashmir" },
  "9857": { operator: "Airtel", circle: "Rajasthan" },
  "9858": { operator: "Airtel", circle: "Jammu & Kashmir" },
  "9859": { operator: "Airtel", circle: "Rajasthan" },
  "9860": { operator: "Airtel", circle: "Maharashtra" },
  "9861": { operator: "Airtel", circle: "Odisha" },
  "9862": { operator: "Airtel", circle: "Assam" },
  "9863": { operator: "Airtel", circle: "Northeast" },
  "9864": { operator: "Airtel", circle: "Assam" },
  "9865": { operator: "Airtel", circle: "Tamil Nadu" },
  "9866": { operator: "Airtel", circle: "Andhra Pradesh" },
  "9867": { operator: "Airtel", circle: "Mumbai" },
  "9868": { operator: "Airtel", circle: "Delhi" },
  "9869": { operator: "Airtel", circle: "Mumbai" },
  "9870": { operator: "Airtel", circle: "Mumbai" },
  "9871": { operator: "Airtel", circle: "Delhi" },
  "9872": { operator: "Airtel", circle: "Punjab" },
  "9873": { operator: "Airtel", circle: "Delhi" },
  "9874": { operator: "Airtel", circle: "West Bengal" },
  "9875": { operator: "Airtel", circle: "West Bengal" },
  "9876": { operator: "Airtel", circle: "Punjab" },
  "9877": { operator: "Airtel", circle: "Punjab" },
  "9878": { operator: "Airtel", circle: "Punjab" },
  "9879": { operator: "Airtel", circle: "Gujarat" },
  "9880": { operator: "Airtel", circle: "Karnataka" },
  "9881": { operator: "Airtel", circle: "Maharashtra" },
  "9882": { operator: "Airtel", circle: "Jammu & Kashmir" },
  "9883": { operator: "Airtel", circle: "West Bengal" },
  "9884": { operator: "Airtel", circle: "Tamil Nadu" },
  "9885": { operator: "Airtel", circle: "Andhra Pradesh" },
  "9886": { operator: "Airtel", circle: "Karnataka" },
  "9887": { operator: "Airtel", circle: "Rajasthan" },
  "9888": { operator: "Airtel", circle: "Punjab" },
  "9889": { operator: "Airtel", circle: "UP East" },
  "9890": { operator: "Airtel", circle: "Maharashtra" },
  "9891": { operator: "Airtel", circle: "Delhi" },
  "9892": { operator: "Airtel", circle: "Mumbai" },
  "9893": { operator: "Airtel", circle: "Madhya Pradesh" },
  "9894": { operator: "Airtel", circle: "Tamil Nadu" },
  "9895": { operator: "Airtel", circle: "Kerala" },
  "9896": { operator: "Airtel", circle: "Haryana" },
  "9897": { operator: "Airtel", circle: "UP West" },
  "9898": { operator: "Airtel", circle: "Gujarat" },
  "9899": { operator: "Airtel", circle: "Delhi" },
  "9900": { operator: "Airtel", circle: "Karnataka" },
  "9901": { operator: "Airtel", circle: "Karnataka" },
  "9902": { operator: "Airtel", circle: "Karnataka" },
  "9903": { operator: "Airtel", circle: "West Bengal" },
  "9904": { operator: "Airtel", circle: "Gujarat" },
  "9905": { operator: "Airtel", circle: "Bihar" },
  "9906": { operator: "Airtel", circle: "Jammu & Kashmir" },
  "9907": { operator: "Airtel", circle: "Madhya Pradesh" },
  "9908": { operator: "Airtel", circle: "Andhra Pradesh" },
  "9909": { operator: "Airtel", circle: "Gujarat" },
  "9910": { operator: "Airtel", circle: "Delhi" },
  "9911": { operator: "Airtel", circle: "Delhi" },
  "9912": { operator: "Airtel", circle: "Delhi" },
  "9913": { operator: "Airtel", circle: "Gujarat" },
  "9914": { operator: "Airtel", circle: "Punjab" },
  "9915": { operator: "Airtel", circle: "Punjab" },
  "9916": { operator: "Airtel", circle: "Karnataka" },
  "9917": { operator: "Airtel", circle: "UP West" },
  "9918": { operator: "Airtel", circle: "UP East" },
  "9919": { operator: "Airtel", circle: "UP East" },
  "9920": { operator: "Airtel", circle: "Mumbai" },
  "9921": { operator: "Airtel", circle: "Maharashtra" },
  "9922": { operator: "Airtel", circle: "Maharashtra" },
  "9923": { operator: "Airtel", circle: "Maharashtra" },
  "9924": { operator: "Airtel", circle: "Gujarat" },
  "9925": { operator: "Airtel", circle: "Gujarat" },
  "9926": { operator: "Airtel", circle: "Madhya Pradesh" },
  "9927": { operator: "Airtel", circle: "UP West" },
  "9928": { operator: "Airtel", circle: "Rajasthan" },
  "9929": { operator: "Airtel", circle: "Rajasthan" },
  "9930": { operator: "Airtel", circle: "Mumbai" },
  "9931": { operator: "Airtel", circle: "Bihar" },
  "9932": { operator: "Airtel", circle: "West Bengal" },
  "9933": { operator: "Airtel", circle: "West Bengal" },
  "9934": { operator: "Airtel", circle: "Bihar" },
  "9935": { operator: "Airtel", circle: "UP East" },
  "9936": { operator: "Airtel", circle: "UP East" },
  "9937": { operator: "Airtel", circle: "Odisha" },
  "9938": { operator: "Airtel", circle: "Odisha" },
  "9939": { operator: "Airtel", circle: "UP East" },
  // ── Vi (Vodafone Idea) ────────────────────────────────
  "9426": { operator: "Vi", circle: "Gujarat" },
  "9427": { operator: "Vi", circle: "Gujarat" },
  "9428": { operator: "Vi", circle: "Gujarat" },
  "9429": { operator: "Vi", circle: "Gujarat" },
  "9712": { operator: "Vi", circle: "Gujarat" },
  "9714": { operator: "Vi", circle: "Gujarat" },
  "9725": { operator: "Vi", circle: "Gujarat" },
  "9727": { operator: "Vi", circle: "Gujarat" },
  "9730": { operator: "Vi", circle: "Maharashtra" },
  "9731": { operator: "Vi", circle: "Karnataka" },
  "9741": { operator: "Vi", circle: "Karnataka" },
  "9742": { operator: "Vi", circle: "Karnataka" },
  "9743": { operator: "Vi", circle: "Karnataka" },
  "9964": { operator: "Vi", circle: "Karnataka" },
  "9980": { operator: "Vi", circle: "Karnataka" },
  "9342": { operator: "Vi", circle: "Tamil Nadu" },
  "9344": { operator: "Vi", circle: "Tamil Nadu" },
  "9345": { operator: "Vi", circle: "Tamil Nadu" },
  "9360": { operator: "Vi", circle: "Tamil Nadu" },
  "9362": { operator: "Vi", circle: "Tamil Nadu" },
  "9384": { operator: "Vi", circle: "Tamil Nadu" },
  "9385": { operator: "Vi", circle: "Tamil Nadu" },
  "9562": { operator: "Vi", circle: "Kerala" },
  "9746": { operator: "Vi", circle: "Kerala" },
  "9747": { operator: "Vi", circle: "Kerala" },
  "9400": { operator: "Vi", circle: "Kerala" },
  "9495": { operator: "Vi", circle: "Kerala" },
  "9496": { operator: "Vi", circle: "Kerala" },
  "9497": { operator: "Vi", circle: "Kerala" },
  "9072": { operator: "Vi", circle: "Kerala" },
  "9745": { operator: "Vi", circle: "Kerala" },
  "8943": { operator: "Vi", circle: "Kerala" },
  // ── BSNL ─────────────────────────────────────────────
  "9418": { operator: "BSNL", circle: "Himachal Pradesh" },
  "9419": { operator: "BSNL", circle: "Jammu & Kashmir" },
  "9436": { operator: "BSNL", circle: "Northeast" },
  "9437": { operator: "BSNL", circle: "Odisha" },
  "9438": { operator: "BSNL", circle: "Odisha" },
  "9439": { operator: "BSNL", circle: "Odisha" },
  "9435": { operator: "BSNL", circle: "Assam" },
  "9431": { operator: "BSNL", circle: "Bihar" },
  "9430": { operator: "BSNL", circle: "Bihar" },
  "9446": { operator: "BSNL", circle: "Kerala" },
  "9447": { operator: "BSNL", circle: "Kerala" },
  "9448": { operator: "BSNL", circle: "Karnataka" },
  "9449": { operator: "BSNL", circle: "Karnataka" },
  "9450": { operator: "BSNL", circle: "UP East" },
  "9451": { operator: "BSNL", circle: "UP East" },
  "9452": { operator: "BSNL", circle: "UP East" },
  "9453": { operator: "BSNL", circle: "UP East" },
  "9454": { operator: "BSNL", circle: "UP East" },
  "9455": { operator: "BSNL", circle: "UP East" },
  "9456": { operator: "BSNL", circle: "UP West" },
  "9457": { operator: "BSNL", circle: "UP West" },
  "9458": { operator: "BSNL", circle: "UP West" },
  "9459": { operator: "BSNL", circle: "UP West" },
  "9460": { operator: "BSNL", circle: "Rajasthan" },
  "9461": { operator: "BSNL", circle: "Rajasthan" },
  "9462": { operator: "BSNL", circle: "Rajasthan" },
  "9463": { operator: "BSNL", circle: "Punjab" },
  "9464": { operator: "BSNL", circle: "Punjab" },
  "9465": { operator: "BSNL", circle: "Punjab" },
  "9416": { operator: "BSNL", circle: "Haryana" },
  "9466": { operator: "BSNL", circle: "Haryana" },
  "9467": { operator: "BSNL", circle: "Haryana" },
  "9468": { operator: "BSNL", circle: "Haryana" },
  "9469": { operator: "BSNL", circle: "Haryana" },
  "9417": { operator: "BSNL", circle: "Punjab" },
  "9473": { operator: "BSNL", circle: "Bihar" },
  "9474": { operator: "BSNL", circle: "West Bengal" },
  "9476": { operator: "BSNL", circle: "Northeast" },
  "9477": { operator: "BSNL", circle: "West Bengal" },
  "9478": { operator: "BSNL", circle: "Northeast" },
  "9479": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9424": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9425": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9407": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9406": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9229": { operator: "BSNL", circle: "Madhya Pradesh" },
  "9414": { operator: "BSNL", circle: "Rajasthan" },
  "9486": { operator: "BSNL", circle: "Tamil Nadu" },
  "9487": { operator: "BSNL", circle: "Tamil Nadu" },
  "9488": { operator: "BSNL", circle: "Tamil Nadu" },
  "9489": { operator: "BSNL", circle: "Tamil Nadu" },
  "9490": { operator: "BSNL", circle: "Andhra Pradesh" },
  "9491": { operator: "BSNL", circle: "Andhra Pradesh" },
  "9622": { operator: "BSNL", circle: "Jammu & Kashmir" },
  "9596": { operator: "BSNL", circle: "Jammu & Kashmir" },
};

function guessBySeries(digits: string): { operator: string; circle: string } {
  const p = digits.substring(0, 2);
  if (digits[0] === "6") return { operator: "Jio (likely)", circle: "Unknown" };
  if (["70","71","72","73","74","75","76","77","78","79"].includes(p)) return { operator: "Jio / Airtel / Vi", circle: "Unknown" };
  if (digits[0] === "8") return { operator: "Airtel / Vi / Jio / BSNL", circle: "Unknown" };
  return { operator: "Airtel / Vi / BSNL / Jio", circle: "Unknown" };
}

export interface IndiaPhoneInfo {
  number: string;
  formattedNumber: string;
  countryCode: string;
  countryName: string;
  operator: string;
  circle: string;
  numberType: string;
  isValid: boolean;
  isPossible: boolean;
  mobilePrefix: string;
  note: string;
}

export function lookupIndiaPhone(rawNumber: string): IndiaPhoneInfo {
  const digits = rawNumber.replace(/[\s\-\(\)]/g, "").replace(/^\+91/, "").replace(/^91/, "");
  const prefix4 = digits.substring(0, 4);

  let isValid = false;
  let isPossible = false;
  let numberType = "Mobile";
  let formattedNumber = `+91 ${digits.substring(0, 5)} ${digits.substring(5)}`.trim();

  try {
    const parsed = parsePhoneNumber(`+91${digits}`);
    isValid = parsed?.isValid() ?? false;
    isPossible = parsed?.isPossible() ?? false;
    formattedNumber = parsed?.formatInternational() ?? formattedNumber;
    const t = parsed?.getType();
    numberType = t === "MOBILE" ? "Mobile" : t === "FIXED_LINE" ? "Landline" : t === "TOLL_FREE" ? "Toll-Free" : (t ?? "Mobile");
  } catch { /* ignore */ }

  const prefixData = PREFIX_MAP[prefix4] ?? guessBySeries(digits);

  return {
    number: digits,
    formattedNumber,
    countryCode: "+91",
    countryName: "India",
    operator: prefixData.operator,
    circle: prefixData.circle,
    numberType,
    isValid,
    isPossible,
    mobilePrefix: prefix4,
    note: "Due to MNP (Mobile Number Portability), current operator may differ from original allocation.",
  };
}
